# Generated by Django 4.2.5 on 2023-10-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainunit',
            options={'ordering': ('name',), 'verbose_name': 'звено цепи', 'verbose_name_plural': 'звенья цепи'},
        ),
        migrations.AlterField(
            model_name='chainunit',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chain.chainunit', verbose_name='поставщик'),
        ),
    ]
