# Generated by Django 4.2.5 on 2023-10-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0004_alter_chainunit_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('model_name', models.CharField(max_length=150, verbose_name='модель')),
                ('issue_date', models.DateField(verbose_name='дата выхода на рынок')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.chainunit', verbose_name='магазин')),
            ],
        ),
    ]
