# Generated by Django 4.2.5 on 2023-10-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0005_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainunit',
            options={'ordering': ('name',), 'verbose_name': 'объект сети', 'verbose_name_plural': 'объекты сети'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
