# Generated by Django 4.2.5 on 2023-10-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0006_alter_chainunit_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainunit',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='задолженность перед поставщиком'),
        ),
    ]
